### ISSUE TITLE
ReadME instructions on how to clone repo has broken link

### ISSUE THREAD

**Issue by igocooper** [leveluptuts/Level-Up-JavaScript-Testing-101#1]
Suggest to change clone link: 

https://github.com/**stolinski**/Level-Up-JavaScript-Testing-101.git
into 
https://github.com/**leveluptuts**/Level-Up-JavaScript-Testing-101.git

```
git clone https://github.com/leveluptuts/Level-Up-JavaScript-Testing-101.git
```

**Comment by stolinski** [comment]
whooosies. THanks!
