### ISSUE TITLE
Jest: SecurityError: localStorage is not available for opaque origins

### ISSUE THREAD

**Issue by mtliendo** [leveluptuts/Level-Up-JavaScript-Testing-101#3]
When using yarn (assuming the same when using NPM), on video 2, users will likely encounter 
` SecurityError: localStorage is not available for opaque origins` when running the jest command.

To solve this issue, please add the following to your `package.json`:
```
"jest": {
    "testEnvironment": "node"
  }
```

Click [here](https://github.com/Microsoft/vscode-recipes/issues/119) for further details into this issue.

**Comment by Matt-Owens** [comment]
For what it's worth, adding this to jest config also worked for me:

```
"jest": {
   testURL: 'http://localhost'
}
```
